# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Roadcaptain"
license = "Creative 2.0"
licenselink = "https://github.com/sandermvanvliet/RoadCaptain/blob/master/LICENSE"
description = ""
homepage = "https://roadcaptain.nl/"
tags = []
features = ["font-awesome","favicon","responsive","sass","scss"]
min_version = "0.67.3 Extended"

[author]
  name = "Sander van Vliet"
  homepage = "https://codenizer.nl"

# If porting an existing theme
[original]
    name = "caressofsteel"
    homepage = "https://github.com/caressofsteel"
    repo = "https://github.com/caressofsteel/hugo-story"
