baseURL = 'https://roadcaptain.nl/'
languageCode = 'en-us'
title = 'RoadCaptain a Zwift custom route builder'
theme = "roadcaptain"

disableKinds = ["taxonomy", "taxonomyTerm", "section"]


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  author = "Sander van vliet"
  description = "Zwift custom route builder"
  logo = "images/banner.jpg"
  favicon = false
  keywords = "Zwift,RoadCaptain,Zwift custom route,road captain,cycling,Zwift Companion"

[Params.social]
  github = "https://github.com/sandermvanvliet/"
  twitter = ""
  email = "info@roadcaptain.nl"
  instagram = ""
  linkedin = ""
  telegram = ""