name: build-and-test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - site/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - site/**

jobs:
  build_win:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: dotnet build --verbosity normal -c Release -p:SkipInvalidConfigurations=true
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

  build_macos-x64:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: dotnet build --verbosity normal -c Release -p:SkipInvalidConfigurations=true -p:EnableWindowsTargeting=true
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release