name: build-api-dev

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - site/**

jobs:
  build_api_linux-x64:

    runs-on: ubuntu-latest

    env:
      CONFIGURATION: Debug
      RID: linux-x64

    steps:
    - uses: actions/checkout@v3
    - name: Publish API
      # Because of reasons we need to explicitly set RuntimeIdentifiers to only win-x64 because MSBuild sets it to osx-x64;win-x64
      run: dotnet publish --self-contained -c ${{ env.CONFIGURATION }} -r ${{ env.RID }} -p:RuntimeIdentifiers=${{ env.RID }} src/RoadCaptain.App.Web/RoadCaptain.App.Web.csproj
    - name: Create ZIP archive
      run: tar -zcf "${{ env.GITHUB_WORKSPACE }}/roadcaptain-app-web-${{ env.GITHUB_SHA }}.tar.gz" *
      working-directory: src/RoadCaptain.App.Web/RoadCaptain.App.Web/bin/${{ env.CONFIGURATION }}/net6.0/linux-x64/publish
    - name: Copy artifacts to server
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: scp -r -o "StrictHostKeyChecking no" ./roadcaptain-app-web-${{ env.GITHUB_SHA }}.tar.gz roadcaptain@roadcaptain.nl:/tmp/roadcaptain-app-web-${{ env.GITHUB_SHA }}.tar.gz
    - name: Extract artifacts on server
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        service stop RoadCaptainApiDev
        cd /opt/roadcaptain/api-dev
        ssh tar -zxf /tmp/roadcaptain-app-web-${{ env.GITHUB_SHA }}.tar.gz
        service start RoadCaptainApiDev