name: build-and-test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - site/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - site/**

jobs:
  build_win:

    runs-on: windows-2022

    env:
      RID: win-x64

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore -r ${{ env.RID }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal -c Release -r ${{ env.RID }} -p:RuntimeIdentifier=${{ env.RID }} -p:RuntimeIdentifiers=${{ env.RID }}

  build_macos-x64:

    runs-on: macos-11

    env:
      RID: osx-x64

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test --verbosity normal -c Release -r ${{ env.RID }} -p:RuntimeIdentifier=${{ env.RID }} -p:RuntimeIdentifiers=${{ env.RID }}