name: build-and-test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - site/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - site/**

jobs:
  build:

    runs-on: windows-2022

    env:
      RID: win-x64

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore -r ${{ env.RID }}
    - name: Test
      run: dotnet test --verbosity normal -c Release -r ${{ env.RID }}
