name: build-and-test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - site/**
  pull_request:
    branches: [ main ]
    paths-ignore:
      - site/**

jobs:
  build_win:

    runs-on: windows-2022

    env:
      RID: win-x64

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore -r ${{ env.RID }}
    - name: Prebuild Windows shared library
      run: dotnet build -c Release -r ${{ env.RID }} --no-self-contained src/RoadCaptain.App.Windows/RoadCaptain.App.Windows.csproj
    - name: Build Runner test project
      run: dotnet build --no-restore --verbosity normal -c Release -r ${{ env.RID }} -p:RuntimeIdentifier=${{ env.RID }} -p:RuntimeIdentifiers=${{ env.RID }} test/RoadCaptain.App.Runner.Tests.Unit/RoadCaptain.App.Runner.Tests.Unit.csproj --no-self-contained
    - name: Test
      run: dotnet test --no-restore --verbosity normal -c Release -r ${{ env.RID }} -p:RuntimeIdentifier=${{ env.RID }} -p:RuntimeIdentifiers=${{ env.RID }}

  build_macos-x64:

    runs-on: macos-11

    env:
      RID: osx-x64

    steps:
    - uses: actions/checkout@v2
    - name: Prebuild macOS shared library
      run: dotnet build -c Release -r ${{ env.RID }} --no-self-contained src/RoadCaptain.App.MacOs/RoadCaptain.App.MacOs.csproj
    - name: Build Runner test project
      run: dotnet build --no-restore --verbosity normal -c Release -r ${{ env.RID }} -p:RuntimeIdentifier=${{ env.RID }} -p:RuntimeIdentifiers=${{ env.RID }} test/RoadCaptain.App.Runner.Tests.Unit/RoadCaptain.App.Runner.Tests.Unit.csproj --no-self-contained
    - name: Test
      run: dotnet test --verbosity normal -c Release -r ${{ env.RID }} -p:RuntimeIdentifier=${{ env.RID }} -p:RuntimeIdentifiers=${{ env.RID }}